spring:
  application:
    name: app
  datasource:
    url: jdbc:sqlite:../database/mydata.sqlite3
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    schema: classpath:/init.sql
  sql:
    init:
      mode: always
      schema-location: classpath:/init.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.todo.api