spring:
  application:
    name: app
  datasource:
    url: jdbc:sqlite:../database/mydata.sqlite3
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    schema: classpath:/init.sql
  sql:
    init:
      mode: always
      schema-location: classpath:/init.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true

jwt:
  secret: jZk5lQ6cM1wTf8XpL-P0dQrV3aBtUsYgJxE7hKm9ZnY
  access-token-validity-in-minutes: 30

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security: DEBUG
    com.todo.api: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    default-models-expand-depth: -1
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.todo.api
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false
  security:
    enabled: true
    paths-to-match:
      - /users/**
      - /todos/**